export const VR_NAME = "velociraptor";
export const VR_MARK = "Generated by Velociraptor";
export const VR_SHELL = "VR_SHELL";
export const VR_LOG = "VR_LOG";
export const VR_HOOKS = "VR_HOOKS";
export const UPGRADE_COMMAND = "vr upgrade";
